---
- name: Remove legacy mpDris2 binary from /usr/local/bin
  ansible.builtin.file:
    path: /usr/local/bin/mpDris2
    state: absent
  become: true

- name: Install mpdris2
  ansible.builtin.apt:
    name:
      - mpdris2
      - python3-mutagen
    state: present
    update_cache: true
    install_recommends: false
  become: true
  notify: Restart mpDris2

- name: Create mpDris2 config directory
  ansible.builtin.file:
    path: "/home/{{ target_user }}/.config/mpDris2"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0700'
  become: true

- name: Create mpDris2 config file
  ansible.builtin.template:
    src: mpDris2.conf.j2
    dest: "/home/{{ target_user }}/.config/mpDris2/mpDris2.conf"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0700'
  become: true
  notify: Restart mpDris2

- name: Enable user mpDris2 service
  ansible.builtin.include_tasks: "../../../tasks/systemd_enable_user.yml"
  vars:
    service_name: mpDris2.service
