---
# Variables par défaut
target_hostname: "{{ ansible_hostname }}"
target_user: "{{ ansible_user_id }}"
spotifyd_version: "0.3.5"
odio_gpg: "https://apt.odio.love/key.gpg"
gpg_file: "/usr/share/keyrings/odio.gpg"

# Core components (default: enabled)
install_pulseaudio: true
install_bluetooth: true
install_mpd: true
install_odio_api: true

# Optional components (default: disabled)
install_spotifyd: false
install_shairport_sync: false
install_snapclient: false
install_upmpdcli: false
install_mpd_discplayer: false
