---
- name: Install spotifyd
  ansible.builtin.apt:
    name: spotifyd
    state: present
    update_cache: false
  become: true
  notify: Restart spotifyd

- name: Create spotifyd config directory
  ansible.builtin.file:
    path: "/home/{{ target_user }}/.config/spotifyd"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  become: true

- name: Deploy spotifyd config
  ansible.builtin.template:
    src: spotifyd.conf.j2
    dest: "/home/{{ target_user }}/.config/spotifyd/spotifyd.conf"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0644'
  become: true
  notify: Restart spotifyd

- name: Enable user spotifyd service
  ansible.builtin.include_tasks: "../../../tasks/systemd_enable_user.yml"
  vars:
    service_name: spotifyd.service
