---
- name: Install spotifyd
  ansible.builtin.apt:
    name: spotifyd
    state: present
  become: true
  register: spotifyd_install
  notify: Restart spotifyd

- name: Upgrade spotifyd
  ansible.builtin.apt:
    name: spotifyd
    only_upgrade: true
  become: true
  notify: Restart spotifyd
  when: not spotifyd_install.changed

- name: Create spotifyd config directory
  ansible.builtin.file:
    path: "/home/{{ target_user }}/.config/spotifyd"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0755'
  become: true

- name: Backup spotifyd config before changes
  ansible.builtin.include_tasks: "../../../tasks/backup_conf_before.yml"
  vars:
    conf_path: "/home/{{ target_user }}/.config/spotifyd/spotifyd.conf"
    conf_owner: "{{ target_user }}"
    conf_group: "{{ target_user }}"
    conf_mode: '0644'

- name: Deploy spotifyd config
  ansible.builtin.template:
    src: spotifyd.conf.j2
    dest: "/home/{{ target_user }}/.config/spotifyd/spotifyd.conf"
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0644'
  become: true
  notify: Restart spotifyd

- name: Backup spotifyd config after changes
  ansible.builtin.include_tasks: "../../../tasks/backup_conf_after.yml"
  vars:
    conf_path: "/home/{{ target_user }}/.config/spotifyd/spotifyd.conf"
    conf_owner: "{{ target_user }}"
    conf_group: "{{ target_user }}"
    conf_mode: '0644'

- name: Enable user spotifyd service
  ansible.builtin.include_tasks: "../../../tasks/systemd_enable_user.yml"
  vars:
    service_name: spotifyd.service
