---
- name: Install Bluetooth packages
  ansible.builtin.apt:
    name:
      - bluez
      - pulseaudio-module-bluetooth
    state: present
  become: true
  notify: Restart bluetooth

- name: Ensure bluetooth group exists
  ansible.builtin.group:
    name: bluetooth
    state: present
  become: true

- name: Ensure user in bluetooth group
  ansible.builtin.user:
    name: "{{ target_user }}"
    append: true
    groups:
      - bluetooth
  become: true

- name: Backup Bluetooth config before changes
  ansible.builtin.include_tasks: "../../../tasks/backup_conf_before.yml"
  vars:
    conf_path: /etc/bluetooth/main.conf

- name: Configure Bluetooth main.conf
  ansible.builtin.template:
    src: bluetooth-main.conf.j2
    dest: /etc/bluetooth/main.conf
    mode: '0644'
  become: true
  notify: Restart bluetooth

- name: Backup Bluetooth config after changes
  ansible.builtin.include_tasks: "../../../tasks/backup_conf_after.yml"
  vars:
    conf_path: /etc/bluetooth/main.conf

- name: Enable Bluetooth service
  ansible.builtin.include_tasks: "../../../tasks/systemd_enable_system.yml"
  vars:
    service_name: bluetooth.service
