---
- name: Restart mpd-discplayer
  ansible.builtin.systemd:
    name: mpd-discplayer.service
    state: restarted
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ target_user_uid }}"
  become: "{{ become_for_target_user }}"
  become_user: "{{ target_user }}"
  when: install_mode == "live"
