---
- name: Install snapclient
  ansible.builtin.apt:
    name: snapclient
    state: present
    install_recommends: false
  become: true
  notify: Restart snapclient

- name: Backup snapclient config before changes
  ansible.builtin.include_tasks: "../../../tasks/backup_conf_before.yml"
  vars:
    conf_path: /etc/default/snapclient

- name: Configure snapclient default options
  ansible.builtin.copy:
    content: 'SNAPCLIENT_OPTS="--player pulse"'
    dest: /etc/default/snapclient
    mode: '0644'
    owner: root
    group: root
  become: true
  notify: Restart snapclient

- name: Backup snapclient config after changes
  ansible.builtin.include_tasks: "../../../tasks/backup_conf_after.yml"
  vars:
    conf_path: /etc/default/snapclient

- name: Disable system snapclient service
  ansible.builtin.include_tasks: "../../../tasks/systemd_disable_system.yml"
  vars:
    service_name: snapclient.service

- name: Copy user snapclient service
  ansible.builtin.copy:
    src: snapclient.service
    dest: /usr/lib/systemd/user/snapclient.service
    mode: '0644'
    owner: root
    group: root
  become: true

- name: Enable user snapclient service
  ansible.builtin.include_tasks: "../../../tasks/systemd_enable_user.yml"
  vars:
    service_name: snapclient.service
