---
# Variables par défaut
install_mode: "live"  # live | image
target_hostname: "{{ ansible_hostname }}"
target_user: "{{ ansible_user_id }}"
odio_gpg: "https://apt.odio.love/key.gpg"
gpg_file: "/usr/share/keyrings/odio.gpg"

odio_version: "unknown"
mpd_music_directory: "/media/USB"

# Core components (default: enabled)
install_pulseaudio: true
install_bluetooth: true
install_mpd: true
install_odio_api: true

# Optional components
install_mpd_discplayer: true
install_shairport_sync: true
install_snapclient: true
install_upmpdcli: true
install_mympd: false
install_tidal: false
install_qobuz: false
install_spotifyd: false
install_upnpwebradios: false

# Branding (odio-motd login banner, hushlogin, .profile hook)
install_branding: false
