---
- name: Restart pulseaudio
  ansible.builtin.systemd:
    name: pulseaudio.service
    state: restarted
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ target_user_uid }}"
  become: true
  become_user: "{{ target_user }}"
