---
- name: Restart pipewire-pulse
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ target_user_uid }}"
  loop:
    - pipewire.service
    - pipewire-pulse.service
    - wireplumber.service
  become: true
  become_user: "{{ target_user }}"
