---
- name: Install shairport-sync
  ansible.builtin.apt:
    name: shairport-sync
    state: present
    install_recommends: false
  become: true
  notify: Restart shairport-sync

- name: Backup shairport-sync config before changes
  ansible.builtin.include_tasks: "../../../tasks/backup_conf_before.yml"
  vars:
    conf_path: /etc/shairport-sync.conf

- name: Configure shairport-sync name
  ansible.builtin.lineinfile:
    path: /etc/shairport-sync.conf
    regexp: '^\s*//?\s*name\s*='
    line: '	name = "%h";'
  become: true
  notify: Restart shairport-sync

- name: Configure shairport-sync output backend
  ansible.builtin.lineinfile:
    path: /etc/shairport-sync.conf
    regexp: '^\s*//?\s*output_backend\s*='
    line: '	output_backend = "pa";'
  become: true
  notify: Restart shairport-sync

- name: Configure shairport-sync mdns backend
  ansible.builtin.lineinfile:
    path: /etc/shairport-sync.conf
    regexp: '^\s*//?\s*mdns_backend\s*='
    line: '	mdns_backend = "avahi";'
  become: true
  notify: Restart shairport-sync

- name: Configure shairport-sync pulseaudio server
  ansible.builtin.lineinfile:
    path: /etc/shairport-sync.conf
    regexp: '^\s*//?\s*server\s*=\s*"host"'
    line: '	server = "127.0.0.1";'
  become: true
  notify: Restart shairport-sync

- name: Configure shairport-sync application name
  ansible.builtin.lineinfile:
    path: /etc/shairport-sync.conf
    regexp: '^\s*//?\s*application_name\s*='
    line: '	application_name = "Shairport Sync";'
  become: true
  notify: Restart shairport-sync

- name: Backup shairport-sync config after changes
  ansible.builtin.include_tasks: "../../../tasks/backup_conf_after.yml"
  vars:
    conf_path: /etc/shairport-sync.conf

- name: Configure dbus policy for shairport-sync
  ansible.builtin.blockinfile:
    path: /usr/share/dbus-1/system.d/shairport-sync-dbus-policy.conf
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: '<busconfig>'
    block: |
        <policy user="{{ target_user }}">
          <allow own="org.gnome.ShairportSync"/>
        </policy>
  become: true
  notify: Reload dbus

- name: Configure dbus policy for shairport-sync MPRIS
  ansible.builtin.blockinfile:
    path: /usr/share/dbus-1/system.d/shairport-sync-mpris-policy.conf
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: '<busconfig>'
    block: |
        <policy user="{{ target_user }}">
          <allow own="org.mpris.MediaPlayer2.ShairportSync"/>
        </policy>
  become: true
  notify: Reload dbus

- name: Deploy shairport-sync user service
  ansible.builtin.copy:
    src: shairport-sync.service
    dest: /usr/lib/systemd/user/shairport-sync.service
    mode: '0644'
    owner: root
    group: root
  become: true

- name: Disable system shairport-sync service
  ansible.builtin.include_tasks: "../../../tasks/systemd_disable_system.yml"
  vars:
    service_name: shairport-sync.service

- name: Enable user shairport-sync service
  ansible.builtin.include_tasks: "../../../tasks/systemd_enable_user.yml"
  vars:
    service_name: shairport-sync.service
